
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: barker_app_development

test:
  <<: *default
  database: barker_app_test

production:
  <<: *default
  database: barker_app_production
  username: barker_app
  password: <%= ENV['BARKER_APP_DATABASE_PASSWORD'] %>
